import { createInventoryItem } from "../core/inventory.js";

export const providerConfigs = [
  { id: "runpod", name: "Runpod", envVars: ["RUNPOD_API_KEY"], supportsLive: true },
  { id: "vast-ai", name: "Vast.ai", envVars: ["VAST_API_KEY"], supportsLive: true },
  { id: "shadeform", name: "Shadeform", envVars: ["SHADEFORM_API_KEY"], supportsLive: true },
  { id: "prime-intellect", name: "Prime Intellect", envVars: ["PRIME_INTELLECT_API_KEY"], supportsLive: true },
  { id: "lambda", name: "Lambda", envVars: ["LAMBDA_API_KEY"], supportsLive: true },
  { id: "crusoe", name: "Crusoe", envVars: ["CRUSOE_ACCESS_KEY", "CRUSOE_SECRET_KEY"], supportsLive: true },
  { id: "cudo", name: "CUDO Compute", envVars: ["CUDO_API_KEY"], supportsLive: true },
  { id: "sesterce", name: "Sesterce", envVars: ["SESTERCE_API_KEY"], supportsLive: true },
  { id: "clore-ai", name: "Clore.ai", envVars: ["CLORE_API_KEY"], supportsLive: true },
  { id: "together-ai", name: "Together AI", envVars: ["TOGETHER_API_KEY"], supportsLive: true },
  { id: "google-cloud", name: "Google Cloud", envVars: ["GOOGLE_CLOUD_API_KEY", "GCP_BILLING_API_KEY", "GCP_ACCESS_TOKEN", "GCP_USE_GCLOUD_AUTH"], supportsLive: true },
  { id: "google-tpu", name: "Google Cloud TPU", envVars: ["GOOGLE_CLOUD_API_KEY", "GCP_BILLING_API_KEY", "GCP_ACCESS_TOKEN", "GCP_USE_GCLOUD_AUTH"], supportsLive: true },
  { id: "aws", name: "AWS", envVars: ["AWS_GPU_INVENTORY_ENABLED", "AWS_ACCESS_KEY_ID", "AWS_PROFILE", "AWS_WEB_IDENTITY_TOKEN_FILE", "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI", "AWS_CONTAINER_CREDENTIALS_FULL_URI"], supportsLive: true },
  { id: "azure", name: "Azure", envVars: ["AZURE_GPU_INVENTORY_ENABLED", "AZURE_SUBSCRIPTION_ID", "AZURE_ACCESS_TOKEN", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_TENANT_ID", "AZURE_FEDERATED_TOKEN_FILE"], supportsLive: true },
  { id: "oci", name: "Oracle OCI", envVars: ["OCI_GPU_INVENTORY_ENABLED", "OCI_CONFIG_FILE", "OCI_PROFILE", "OCI_TENANCY_OCID", "OCI_USER_OCID", "OCI_FINGERPRINT", "OCI_PRIVATE_KEY", "OCI_PRIVATE_KEY_FILE", "OCI_RESOURCE_PRINCIPAL_VERSION"], supportsLive: true },
  { id: "nebius", name: "Nebius", envVars: ["NEBIUS_ENABLED", "NEBIUS_TENANT_ID", "NEBIUS_PROJECT_ID", "NEBIUS_PROJECT_IDS", "NEBIUS_PROFILE"], supportsLive: true },
  { id: "hyperstack", name: "Hyperstack", envVars: ["HYPERSTACK_API_KEY"], supportsLive: true },
  { id: "voltage-park", name: "Voltage Park", envVars: ["VOLTAGE_PARK_API_KEY", "VOLTAGEGPU_API_KEY"], supportsLive: true },
  { id: "verda-datacrunch", name: "Verda/DataCrunch", envVars: ["DATACRUNCH_CLIENT_ID", "DATACRUNCH_CLIENT_SECRET", "DATACRUNCH_API_KEY"], supportsLive: true },
  { id: "vultr", name: "Vultr", envVars: ["VULTR_API_KEY"], supportsLive: true },
  { id: "scaleway", name: "Scaleway", envVars: ["SCW_SECRET_KEY", "SCW_ACCESS_KEY", "SCW_PROJECT_ID", "SCW_ZONES"], supportsLive: true },
  { id: "tensordock", name: "TensorDock", envVars: ["TENSORDOCK_API_TOKEN"], supportsLive: true },
  { id: "latitude", name: "Latitude.sh", envVars: ["LATITUDE_API_KEY", "LATITUDESH_BEARER"], supportsLive: true },
  { id: "gmi", name: "GMI Cloud", envVars: ["GMI_API_KEY"], supportsLive: true },
  { id: "gcore", name: "Gcore", envVars: ["GCORE_API_KEY"], supportsLive: true },
  { id: "digitalocean", name: "DigitalOcean", envVars: ["DIGITALOCEAN_TOKEN", "DIGITALOCEAN_API_TOKEN", "DO_API_TOKEN", "DIGITALOCEAN_API_KEY"], supportsLive: true },
  { id: "akamai-linode", name: "Akamai/Linode", envVars: ["LINODE_TOKEN", "LINODE_API_TOKEN", "AKAMAI_LINODE_TOKEN", "LINODE_ENABLED"], supportsLive: true },
  { id: "exabits", name: "Exabits", envVars: ["EXABITS_API_TOKEN", "EXABITS_API_KEY"], supportsLive: true },
  { id: "e2e-cloud", name: "E2E Cloud", envVars: ["E2E_API_KEY", "E2E_AUTH_TOKEN"], supportsLive: true },
  { id: "nscale", name: "Nscale", envVars: ["NSCALE_SERVICE_TOKEN", "NSCALE_API_TOKEN", "NSCALE_TOKEN", "NSCALE_ORGANIZATION_ID", "NSCALE_ORGANIZATION_IDS"], supportsLive: true },
  { id: "ovhcloud", name: "OVHcloud", envVars: ["OVH_APPLICATION_KEY", "OVH_APPLICATION_SECRET", "OVH_CONSUMER_KEY", "OVH_PROJECT_ID", "OVH_PUBLIC_CLOUD_PROJECT_ID", "OVH_PUBLIC_CLOUD_PROJECT_IDS"], supportsLive: true },
  { id: "civo", name: "Civo", envVars: ["CIVO_API_KEY", "CIVO_TOKEN"], supportsLive: true },
  { id: "novita", name: "Novita AI", envVars: ["NOVITA_API_KEY", "NOVITA_TOKEN"], supportsLive: true },
  { id: "oblivus", name: "Oblivus", envVars: ["OBLIVUS_API_KEY", "OBLIVUS_TOKEN"], supportsLive: true },
  { id: "leader-gpu", name: "LeaderGPU", envVars: ["LEADERGPU_LOGIN", "LEADERGPU_PASSWORD"], supportsLive: true },
  { id: "thunder-compute", name: "Thunder Compute", envVars: ["THUNDERCOMPUTE_ENABLED", "THUNDER_ENABLED"], supportsLive: true },
  { id: "outscale", name: "Outscale", envVars: ["OUTSCALE_ENABLED"], supportsLive: true },
  { id: "leafcloud", name: "leafcloud", envVars: ["LEAFCLOUD_ENABLED"], supportsLive: true },
  { id: "seeweb", name: "Seeweb", envVars: ["SEEWEB_ENABLED"], supportsLive: true },
  { id: "saladcloud", name: "SaladCloud", envVars: ["SALAD_API_KEY", "SALAD_ORG"], supportsLive: true },
  { id: "jarvis-labs", name: "Jarvis Labs", envVars: ["JARVISLABS_API_KEY", "JARVIS_API_KEY"], supportsLive: true },
  { id: "hydra-host", name: "Hydra Host", envVars: ["HYDRA_ENABLED", "HYDRAHOST_ENABLED"], supportsLive: true },
  { id: "sakura", name: "SAKURA internet", envVars: ["SAKURA_ENABLED", "SAKURACLOUD_ENABLED"], supportsLive: true },
  { id: "ionos", name: "IONOS Cloud", envVars: ["IONOS_ENABLED"], supportsLive: true },
  { id: "sharon-ai", name: "Sharon AI", envVars: ["SHARONAI_API_KEY", "SHARONAI_TOKEN"], supportsLive: true },
  { id: "atlantic-net", name: "Atlantic.Net", envVars: ["ATLANTICNET_ENABLED"], supportsLive: true },
  { id: "gpulist-ai", name: "gpulist.ai", envVars: ["GPULIST_ENABLED"], supportsLive: true },
  { id: "denvr", name: "Denvr Dataworks", envVars: ["DENVR_ACCESS_TOKEN", "DENVR_USERNAME", "DENVR_EMAIL", "DENVR_PASSWORD"], supportsLive: true },
  { id: "contabo", name: "Contabo", envVars: ["CONTABO_ENABLED"], supportsLive: true },
  { id: "hetzner", name: "Hetzner", envVars: ["HETZNER_ENABLED"], supportsLive: true },
  { id: "utho", name: "Utho", envVars: ["UTHO_ENABLED"], supportsLive: true },
  { id: "greennode", name: "GreenNode", envVars: ["GREENNODE_ENABLED"], supportsLive: true },
  { id: "acecloud", name: "ACE Cloud", envVars: ["ACECLOUD_ENABLED"], supportsLive: true },
  { id: "arkane-cloud", name: "Arkane Cloud", envVars: ["ARKANE_ENABLED"], supportsLive: true },
  { id: "hot-aisle", name: "Hot Aisle", envVars: ["HOTAISLE_API_KEY", "HOTAISLE_TOKEN", "HOTAISLE_TEAM_HANDLE"], supportsLive: true },
  { id: "hpc-ai", name: "HPC-AI.com", envVars: ["HPCAI_ENABLED"], supportsLive: true },
  { id: "northflank", name: "Northflank", envVars: ["NORTHFLANK_ENABLED"], supportsLive: true },
  { id: "hivenet", name: "Hivenet", envVars: ["HIVENET_ENABLED"], supportsLive: true },
  { id: "ionstream", name: "ionstream.ai", envVars: ["IONSTREAM_ENABLED"], supportsLive: true },
  { id: "ionet", name: "io.net", envVars: ["IONET_ENABLED"], supportsLive: true },
  { id: "coreweave", name: "CoreWeave", envVars: ["COREWEAVE_ENABLED"], supportsLive: true },
  { id: "liquidweb", name: "LiquidWeb", envVars: ["LIQUIDWEB_ENABLED"], supportsLive: true },
  { id: "qubrid", name: "Qubrid AI", envVars: ["QUBRID_ENABLED"], supportsLive: true },
  { id: "core42", name: "Core42", envVars: ["CORE42_ENABLED"], supportsLive: true },
  { id: "flexai", name: "FlexAI", envVars: ["FLEXAI_ENABLED"], supportsLive: true },
  { id: "valdi", name: "Valdi", envVars: ["VALDI_ENABLED"], supportsLive: true },
  { id: "farmgpu", name: "FarmGPU", envVars: ["FARMGPU_ENABLED"], supportsLive: true },
  { id: "cirrascale", name: "Cirrascale", envVars: ["CIRRASCALE_ENABLED"], supportsLive: true },
  { id: "whitefiber", name: "WhiteFiber", envVars: ["WHITEFIBER_ENABLED"], supportsLive: true },
  { id: "yottalabs", name: "Yotta Labs", envVars: ["YOTTALABS_ENABLED"], supportsLive: true },
  { id: "neysa", name: "Neysa", envVars: ["NEYSA_ENABLED"], supportsLive: true },
  { id: "taiga", name: "Northern Data / Taiga Cloud", envVars: ["TAIGA_ENABLED"], supportsLive: true },
  { id: "olakrutrim", name: "Ola Krutrim", envVars: ["OLAKRUTRIM_ENABLED"], supportsLive: true },
  { id: "zoner", name: "Zoner", envVars: ["ZONER_ENABLED"], supportsLive: true },
  { id: "neevcloud", name: "NeevCloud", envVars: ["NEEVCLOUD_API_KEY", "NEEVCLOUD_PAT", "NEEVCLOUD_TOKEN"], supportsLive: true },
  { id: "getdeploying", name: "getDeploying", envVars: ["GETDEPLOYING_ENABLED"], supportsLive: true },
  { id: "nebulablock", name: "Nebula Block", envVars: ["NEBULABLOCK_ENABLED"], supportsLive: true },
  { id: "trainy", name: "Trainy", envVars: ["TRAINY_ENABLED"], supportsLive: true },
  { id: "turboscale", name: "Turboscale", envVars: ["TURBOSCALE_ENABLED"], supportsLive: true },
  { id: "visionbay", name: "Visionbay", envVars: ["VISIONBAY_ENABLED"], supportsLive: true },
  { id: "cloudclusters", name: "CloudClusters", envVars: ["CLOUDCLUSTERS_ENABLED"], supportsLive: true },
  { id: "airon", name: "Airon", envVars: ["AIRON_ENABLED"], supportsLive: true },
  { id: "ax3", name: "Ax3.Ai", envVars: ["AX3_ENABLED"], supportsLive: true },
  { id: "cato-digital", name: "Cato Digital", envVars: ["CATO_ENABLED"], supportsLive: true },
  { id: "cloudexe", name: "Cloudexe", envVars: ["CLOUDEXE_ENABLED"], supportsLive: true },
  { id: "highreso", name: "HIGHRESO / GPUSOROBAN", envVars: ["HIGHRESO_ENABLED"], supportsLive: true },
  { id: "nodeai", name: "NodeAI", envVars: ["NODEAI_ENABLED"], supportsLive: true },
  { id: "charg", name: "Charg", envVars: ["CHARG_ENABLED"], supportsLive: true },
  { id: "polaris", name: "Polaris", envVars: ["POLARIS_ENABLED"], supportsLive: true },
  { id: "slyd", name: "SLYD", envVars: ["SLYD_ENABLED"], supportsLive: true },
  { id: "massed-compute", name: "Massed Compute", envVars: ["MASSED_COMPUTE_API_KEY"], supportsLive: true },
  { id: "hydra-cloud", name: "Hydra Cloud", envVars: [], supportsLive: false },
  { id: "mithril", name: "Mithril", envVars: ["MITHRIL_API_KEY", "MITHRIL_TOKEN"], supportsLive: true }
];

const rawFixtureOffers = [
  offer("Runpod", "rp-h200-eu-1", "NVIDIA H200 SXM", 8, 4.95, "EU-FR-1", "container", "NVLink", 188, 1500, "https://www.runpod.io/console/gpu-cloud"),
  offer("Runpod", "rp-h100-us-1", "NVIDIA H100 PCIe 80GB", 1, 2.69, "US-GA-1", "container", "PCIe", 24, 128, "https://www.runpod.io/console/gpu-cloud"),
  offer("Vast.ai", "vast-h100-8x-ny", "8x NVIDIA H100 SXM 80GB", 8, 2.31, "New York, US", "bare_metal", "NVLink", 192, 1400, "https://cloud.vast.ai/create/"),
  offer("Vast.ai", "vast-l40s-4x-de", "4x NVIDIA L40S", 4, 0.78, "Germany", "container", "PCIe", 64, 512, "https://cloud.vast.ai/create/"),
  offer("Shadeform", "shade-h200-us", "H200 SXM5 141GB", 8, 4.55, "US East", "vm", "NVLink", 240, 1800, "https://www.shadeform.ai/"),
  offer("Prime Intellect", "pi-h100-ca", "NVIDIA H100 SXM", 8, 2.75, "Canada", "container", "NVLink", 192, 1100, "https://app.primeintellect.ai/"),
  offer("Lambda", "lambda-h100-1x", "1x NVIDIA H100 SXM 80GB", 1, 2.49, "us-west-1", "vm", "NVLink", 26, 200, "https://cloud.lambda.ai/instances"),
  offer("Lambda", "lambda-b200-8x", "8x NVIDIA HGX B200", 8, 6.19, "us-south-1", "vm", "NVLink", 224, 1800, "https://cloud.lambda.ai/instances"),
  offer("Crusoe", "crusoe-h100-8x", "8x H100 SXM", 8, 2.95, "us-east", "vm", "InfiniBand", 176, 2000, "https://cloud.crusoe.ai/"),
  offer("CUDO Compute", "cudo-a100-4x", "4x A100 80GB SXM", 4, 1.39, "UK", "vm", "NVLink", 96, 768, "https://www.cudocompute.com/console"),
  offer("Sesterce", "sesterce-h200-1x-fr", "H200 141GB SXM", 1, 3.58, "France", "vm", "NVLink", 28, 240, "https://cloud.sesterce.com/clusters"),
  offer("Sesterce", "sesterce-h100-8x-eu", "8x H100 80GB", 8, 2.09, "Europe", "vm", "NVLink", 220, 1600, "https://cloud.sesterce.com/clusters"),
  offer("Clore.ai", "clore-4090-1x", "RTX 4090", 1, 0.44, "US", "container", "PCIe", 16, 64, "https://clore.ai/marketplace"),
  offer("Clore.ai", "clore-h100-2x", "2x H100 PCIe 80GB", 2, 2.05, "Europe", "container", "PCIe", 48, 256, "https://clore.ai/marketplace"),
  offer("Hyperstack", "hyper-h200-8x", "8x H200-141G-SXM5", 8, 4.7, "Canada", "vm", "NVLink", 224, 1800, "https://console.hyperstack.cloud/"),
  offer("Voltage Park", "vp-h100-8x", "8x NVIDIA H100 SXM5", 8, 2.88, "North America", "bare_metal", "InfiniBand", 176, 2000, "https://console.voltagepark.com/"),
  offer("AWS", "aws-p5-48xlarge-use1", "8x H100 80GB SXM", 8, 12.29, "us-east-1", "vm", "NVLink", 192, 2048, "https://console.aws.amazon.com/ec2/home?region=us-east-1#LaunchInstances:instanceType=p5.48xlarge"),
  offer("Azure", "azure-nd96isr-h100-eastus-1", "8x H100 SXM 80GB Standard_ND96isr_H100_v5", 8, 7.85, "eastus", "vm", "NVLink", 96, 1900, "https://portal.azure.com/#create/Microsoft.VirtualMachine?region=eastus&size=Standard_ND96isr_H100_v5"),
  offer("Oracle OCI", "oci-bm-gpu-h100-iad-ad1", "8x H100 80GB BM.GPU.H100.8", 8, 6.5, "us-ashburn-1", "bare_metal", "RDMA", 112, 2048, "https://cloud.oracle.com/compute/instances/create?region=us-ashburn-1&shape=BM.GPU.H100.8"),
  offer("Nebius", "nebius-h100-catalog-eu-north1", "8x H100 80GB NVLink", 8, null, "eu-north1", "vm", "NVLink", 128, 1600, "https://console.nebius.com/"),
  offer("GMI Cloud", "gmi-h100-1x", "H100 PCIe", 1, 2.18, "US West", "vm", "PCIe", 26, 180, "https://console.gmicloud.ai/"),
  offer("Verda/DataCrunch", "dc-h200-8x", "8x H200 SXM", 8, 4.35, "Finland, Europe", "vm", "NVLink", 240, 1800, "https://cloud.datacrunch.io/"),
  offer("Scaleway", "scw-h100-1x", "NVIDIA H100 PCIe", 1, 2.99, "fr-par", "vm", "PCIe", 24, 256, "https://console.scaleway.com/"),
  offer("Vultr", "vultr-l40s-1x", "NVIDIA L40S", 1, 0.99, "ewr", "vm", "PCIe", 24, 180, "https://my.vultr.com/deploy/"),
  offer("TensorDock", "td-h100-1x", "NVIDIA H100 SXM 80GB", 1, 2.2, "Austin, US", "vm", "NVLink", 32, 128, "https://dashboard.tensordock.com/deploy"),
  offer("Latitude.sh", "latitude-h100-4x-sao", "4x NVIDIA H100", 4, 2.5, "Brazil / SAO", "bare_metal", "NVLink", 96, 1024, "https://metal.new?plan=gpu-h100-4x&location=SAO"),
  offer("Gcore", "gcore-h100-8x", "H100 SXM 80GB", 8, 3.1, "Luxembourg, Europe", "bare_metal", "InfiniBand", 176, 1600, "https://cloud.gcore.com/"),
  offer("DigitalOcean", "do-h100-1x", "NVIDIA H100", 1, 3.39, "nyc2", "vm", "PCIe", 20, 240, "https://cloud.digitalocean.com/droplets/new"),
  offer("Akamai/Linode", "linode-rtx6000-1x", "RTX 6000 Ada", 1, 1.5, "us-east", "vm", "PCIe", 16, 128, "https://cloud.linode.com/linodes/create"),
  offer("Exabits", "exabits-h200-4x", "4x H200 SXM", 4, 4.15, "US West", "vm", "NVLink", 128, 1024, "https://cloud.exabits.ai/"),
  offer("E2E Cloud", "e2e-a100-1x", "A100 80GB", 1, 1.29, "India", "vm", "PCIe", 16, 115, "https://myaccount.e2enetworks.com/"),
  offer("SaladCloud", "salad-4090-1x", "RTX 4090", 1, 0.55, "North America", "container", "PCIe", 8, 30, "https://portal.salad.com/"),
  offer("Sharon AI", "sharon-h100-8x", "8x H100 SXM", 8, 2.81, "Australia", "bare_metal", "NVLink", 192, 1500, "https://cloud.sharonai.com/"),
  offer("Massed Compute", "massed-h100-1x", "H100 SXM 80GB", 1, 2.4, "US East", "vm", "NVLink", 26, 240, "https://cloud.massedcompute.com/"),
  offer("Hydra Cloud", "hydra-h200-1x", "H200 SXM", 1, 4.25, "Europe", "vm", "NVLink", 32, 320, "https://console.hydracloud.ai/"),
  offer("Mithril", "mithril-b200-1x", "B200", 1, 6.75, "US", "vm", "NVLink", 32, 380, "https://console.mithril.cloud/"),
  offer("Hot Aisle", "hot-aisle-mi300x-8x", "8x MI300X", 8, 1.99, "United States", "vm", "Infinity Fabric", 224, 2048, "https://admin.hotaisle.app/"),
  offer("HPC-AI.com", "hpc-ai-h200-8x", "8x H200 SXM5", 8, 2.5, "Global", "bare_metal", "InfiniBand", 224, 2048, "https://www.hpc-ai.com/gpus/h200"),
  offer("Northflank", "northflank-h100-1x", "H100 80GB", 1, 2.74, "Northflank Managed Cloud", "container", "", 24, 200, "https://northflank.com/pricing"),
  offer("Hivenet", "hivenet-5090-1x", "RTX 5090", 1, 0.82, "france", "vm", "PCIe", 32, 64, "https://console.hivecompute.ai/"),
  offer("ionstream.ai", "ionstream-h200-1x", "H200", 1, 2.06, "ionstream.ai", "bare_metal", "", 141, 256, "https://ionstream.ai/"),
  offer("io.net", "ionet-h100-8x", "8x H100", 8, 27.88, "FI", "vm", "NVLink", 176, 1480, "https://cloud.io.net/"),
  offer("CoreWeave", "coreweave-hgx-h100", "8x HGX H100", 8, 49.24, "CoreWeave Cloud", "bare_metal", "", 128, 2048, "https://www.coreweave.com/pricing"),
  offer("LiquidWeb", "liquidweb-h100-nvl-94gb", "H100 NVL 94GB", 1, 2.98, "LiquidWeb", "bare_metal", "", 0, 0, "https://www.liquidweb.com/gpu-hosting/"),
  offer("Qubrid AI", "qubrid-h100-80gb-1x", "H100", 1, 3.83, "Qubrid Cloud", "vm", "", 16, 200, "https://qubrid.com/pricing"),
  offer("Core42", "core42-h100", "H100", 1, 2.5, "Core42 AI Cloud", "bare_metal", "", 0, 0, "https://www.core42.ai/products/ai-cloud"),
  offer("FlexAI", "flexai-h100-sxm", "H100 SXM", 1, 2.1, "FlexAI", "vm", "", 0, 0, "https://flex.ai/pricing"),
  offer("Valdi", "valdi-h100", "H100", 1, 2.35, "Valdi", "vm", "", 0, 0, "https://www.valdi.ai/"),
  offer("FarmGPU", "farmgpu-h100-8x", "8x H100 80GB SXM", 8, 2.99, "FarmGPU", "bare_metal", "NVLink + RoCE", 0, 0, "https://farmgpu.com/pricing"),
  offer("Cirrascale", "cirrascale-h100-8x", "8x H100", 8, 3.43, "Cirrascale", "bare_metal", "", 0, 0, "https://cirrascale.com/pricing"),
  offer("WhiteFiber", "whitefiber-b200", "B200", 1, 2.5, "WhiteFiber", "bare_metal", "", 0, 0, "https://www.whitefiber.com/pricing"),
  offer("Yotta Labs", "yottalabs-h100", "H100 80GB", 1, 2.56, "Yotta Labs", "container", "", 0, 0, "https://www.yottalabs.ai/pricing"),
  offer("Neysa", "neysa-h100-sxm", "H100 SXM 80GB", 1, 4.39, "Neysa", "vm", "", 0, 0, "https://neysa.ai/pricing"),
  offer("Northern Data / Taiga Cloud", "taiga-h100-sxm-8x", "8x H100 SXM 80GB", 8, 2.4, "Europe", "bare_metal", "InfiniBand", 0, 0, "https://northerndata.de/taiga-cloud-ai-pricing-2026"),
  offer("Ola Krutrim", "olakrutrim-h100-1x", "H100 80GB", 1, 2.56, "India", "vm", "", 0, 0, "https://www.olakrutrim.com/pricing"),
  offer("Zoner", "zoner-rtx4090", "RTX 4090 24GB", 1, 0.3, "Zoner", "vm", "", 0, 0, "https://www.zonercloud.com/ai-gpu/ai-gpu-server"),
  offer("NeevCloud", "neevcloud-h100-80g", "H100 80GB", 1, 1.99, "as-south-1", "container", "", 20, 125, "https://ai.neevcloud.com/"),
  offer("getDeploying", "gd:sample-h100", "H100 80GB", 1, 2.09, "Sesterce", "vm", "", 0, 0, "https://www.getdeploying.com/reference/cloud-gpu/nvidia-h100"),
  offer("Nebula Block", "nebulablock-a100-1x", "A100 80GB PCIe", 1, 1.428, "North America", "vm", "", 28, 120, "https://nebulablock.com/"),
  offer("Trainy", "trainy-h100-8x", "8x H100 80GB", 8, 3.6, "Trainy", "bare_metal", "InfiniBand", 0, 0, "https://www.trainy.ai/pricing"),
  offer("Turboscale", "turboscale-h100-1x", "H100 80GB", 1, 3.24, "Turboscale", "vm", "", 30, 380, "https://www.turboscale.com/pricing"),
  offer("Visionbay", "visionbay-h100", "H100", 1, 4, "Taiwan", "bare_metal", "", 0, 0, "https://visionbay.ai/zh-tw/pricing"),
  offer("CloudClusters", "cloudclusters-h100", "H100", 1, 2.8753, "USA", "bare_metal", "", 36, 256, "https://www.cloudclusters.io/server/gpu"),
  offer("Airon", "airon-h100", "H100 NVL PCIe", 1, 1.88, "Sweden", "vm", "NVLink", 0, 0, "https://www.airon.ai/"),
  offer("Ax3.Ai", "ax3-h200", "H200", 1, 2.5, "Ax3 global regions", "vm", "", 0, 0, "https://www.ax3.ai/pricing"),
  offer("Cato Digital", "cato-g2-large", "8x V100 32GB", 8, 1.3999, "Cato Digital", "bare_metal", "NVSwitch/NVLink", 96, 512, "https://cato.digital/product/gpu/"),
  offer("Cloudexe", "cloudexe-gold-h100", "H100", 1, 2.49, "Cloudexe", "container", "", 0, 0, "https://cloudexe.tech/"),
  offer("HIGHRESO / GPUSOROBAN", "highreso-b200", "8x B200 SXM 180GB", 8, 1320, "Japan", "bare_metal", "InfiniBand", 224, 4096, "https://highreso.jp/en/"),
  offer("NodeAI", "nodeai-a100", "A100", 1, 0.85, "NodeAI marketplace", "container", "", 0, 0, "https://manage.nodes.ai/"),
  offer("Charg", "charg-8x-v100", "8x V100", 8, 2.125, "Dallas, US", "bare_metal", "200 Gbit InfiniBand", 64, 512, "https://charg.cloud/pricing/"),
  offer("Polaris", "polaris-h100-cloud-on-demand", "H100 80GB", 1, 2.748, "Polaris marketplace", "vm", "", 0, 0, "https://polaris.computer/compute"),
  offer("SLYD", "slyd-rtx-a6000-kc", "RTX A6000", 1, 0.5, "Kansas City, MO", "vm", "", 6, 24, "https://slyd.com/Account/Login?redirectUri=/consumer/compute-marketplace&gpu=rtx-a6000")
];

export function fixtureInventory(now = new Date()) {
  return rawFixtureOffers.map((raw, index) => {
    const lastSeenAt = new Date(now.getTime() - (index % 9) * 45_000).toISOString();
    return createInventoryItem({ ...raw, providerId: providerIdByName[raw.provider] || raw.providerId, lastSeenAt, sourceMode: "fixture" });
  });
}

const providerIdByName = Object.fromEntries(providerConfigs.map((provider) => [provider.name, provider.id]));

function offer(provider, rawOfferId, gpuLabel, gpuCount, pricePerGpuHour, region, formFactor, interconnect, cpu, ramGb, checkoutUrl) {
  return {
    provider,
    rawOfferId,
    gpuLabel,
    gpuCount,
    pricePerGpuHour,
    region,
    formFactor,
    interconnect,
    cpu: `${cpu} vCPU`,
    ramGb,
    storage: "provider default",
    availability: "available",
    checkoutUrl,
    deploySupported: false,
    rawPayload: { fixture: true, rawOfferId }
  };
}
